---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"


  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: db_servers
  become: true
  tasks: 

#play for Ubuntu
  - name: install mariadb package (Ubuntu)
    apt:
      name: 
        - mariadb-server   
      state: latest
    when: ansible_distribution == "Ubuntu" 


#play for CentOS
  - name: install mariadb package (CentOS)
    dnf:
      name: 
        - mariadb  
      state: latest 
    when: ansible_distribution == "CentOS" 



- hosts: file_servers
  become: true
  tasks: 

#play for Ubuntu
  - name: install samba package (Ubuntu & CentOS)
    package:
      name: 
        - Samba  
      state: latest 

#to run our playbook
ansible-playbook --ask-become-pass target-specific-nodes.yml