- name: install apache2 package and add php support for apache (Ubuntu)
  tags: apache,apache2,ubuntu
  apt:
    name: 
      - apache2
      - libapache2-mod-php      
    state: latest 
  when: ansible_distribution == "Ubuntu" 


- name: install apache2 package and add php support for apache  (CentOS)
  tags: apache,centos,httpd
  dnf:
    name: 
      - httpd
      - php   
    state: latest 
  when: ansible_distribution == "CentOS"


- name: start httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: 
      - httpd  
    state: started
    enabled: yes 
  when: ansible_distribution == "CentOS"

- name: change email address for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "CentOS"
  register: httpd #register a variable

- name: restart httpd (centos)
  tags: apache,centos,httpd
  service:
    name: 
      - httpd  
    state: restarted
  when: httpd.changed #run this play when the above registered variable is changed


- name: Copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html  
    dest: /var/www/html/index.html
    owner: root
    group: root

