---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"


  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

#Web Servers
- hosts: web_servers
  become: true
  tasks: 

  - name: install apache2 package and add php support for apache (Ubuntu)
    apt:
      name: 
        - apache2
        - libapache2-mod-php      
      state: latest 
    when: ansible_distribution == "Ubuntu" 


  - name: install apache2 package and add php support for apache  (CentOS)
    dnf:
      name: 
        - httpd
        - php   
      state: latest 
    when: ansible_distribution == "CentOS"


#DB Servers
- hosts: db_servers
  become: true
  tasks: 

  - name: install mariadb package (Ubuntu)
    apt:
      name: 
        - mariadb-server   
      state: latest
    when: ansible_distribution == "Ubuntu" 


  - name: install mariadb package (CentOS)
    dnf:
      name: 
        - mariadb  
      state: latest 
    when: ansible_distribution == "CentOS" 


#File Servers
- hosts: file_servers
  become: true
  tasks: 

  - name: install samba package (Ubuntu & CentOS)
    package:
      name: 
        - Samba
      state: latest 

#to run our playbook
ansible-playbook --ask-become-pass target-specific-nodes.yml