---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"


  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

#Web Servers
- hosts: web_servers
  become: true
  tasks: 

  - name: install apache2 package and add php support for apache (Ubuntu)
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php      
      state: latest 
    when: ansible_distribution == "Ubuntu" 


  - name: install apache2 package and add php support for apache  (CentOS)
    tags: apache,centos,httpd
    dnf:
      name: 
        - httpd
        - php   
      state: latest 
    when: ansible_distribution == "CentOS"


#DB Servers
- hosts: db_servers
  become: true
  tasks: 

  - name: install mariadb package (Ubuntu)
    tags: db, mariadb, ubuntu
    apt:
      name: 
        - mariadb-server   
      state: latest
    when: ansible_distribution == "Ubuntu" 


  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: 
        - mariadb  
      state: latest 
    when: ansible_distribution == "CentOS" 


#File Servers
- hosts: file_servers
  become: true
  tasks: 

  - name: install samba package (Ubuntu & CentOS)
    tags: samba
    package:
      name: 
        - Samba  
      state: latest 

#to run our playbook
ansible-playbook --ask-become-pass target-specific-nodes.yml

#to list all tags
ansible-playbook --list-tags working-with-tags.yml

#to target a list of servers with a particular tag
ansible-playbook --tags centos --ask-become-pass working-with-tags.yml

#to target a list of  tags
ansible-playbook --tags "apache,db" --ask-become-pass working-with-tags.yml